"""analysis confidence

Revision ID: 305f4fdc47ae
Revises: a16312ca1083
Create Date: 2026-09-28 00:35:25.463960

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "305f4fdc47ae"
down_revision: str | Sequence[str] | None = "a16312ca1083"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("analyses", sa.Column("confidence", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("analyses", "confidence")
    # ### end Alembic commands ###
