"""initial schema

Enables pgvector, creates all tables, and turns on Row Level Security.

Revision ID: 37ae95149788
Revises:
Create Date: 2026-09-27 18:07:26.594205

"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "37ae95149788"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

TABLES = ("analyses", "reported_entities", "reports", "scam_patterns", "url_cache")


def upgrade() -> None:
    # Must exist before the scam_patterns.embedding column and its HNSW index.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "analyses",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("input_type", sa.Text(), nullable=False),
        sa.Column("raw_input", sa.Text(), nullable=False),
        sa.Column("normalized_text", sa.Text(), nullable=True),
        sa.Column(
            "extracted_entities",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("risk_score", sa.Integer(), nullable=False),
        sa.Column("verdict", sa.Text(), nullable=False),
        sa.Column("scam_type", sa.Text(), nullable=True),
        sa.Column(
            "red_flags",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "signal_breakdown",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("explanation_en", sa.Text(), nullable=True),
        sa.Column("explanation_hi", sa.Text(), nullable=True),
        sa.Column(
            "latency_ms",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "input_type IN ('text', 'upi', 'url', 'qr', 'screenshot')",
            name=op.f("ck_analyses_input_type"),
        ),
        sa.CheckConstraint(
            "verdict IN ('safe', 'suspicious', 'scam')", name=op.f("ck_analyses_verdict")
        ),
        sa.CheckConstraint(
            "risk_score BETWEEN 0 AND 100", name=op.f("ck_analyses_risk_score_range")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_analyses")),
    )
    op.create_index("ix_analyses_created_at", "analyses", ["created_at"], unique=False)
    op.create_table(
        "reported_entities",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("entity_type", sa.Text(), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("report_count", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "first_seen",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_seen", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "is_verified_scam", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "entity_type IN ('upi', 'phone', 'url', 'domain')",
            name=op.f("ck_reported_entities_entity_type"),
        ),
        sa.CheckConstraint(
            "report_count >= 0", name=op.f("ck_reported_entities_report_count_non_negative")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reported_entities")),
        sa.UniqueConstraint(
            "entity_type", "value", name=op.f("uq_reported_entities_entity_type_value")
        ),
    )
    op.create_table(
        "scam_patterns",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("category", sa.Text(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("content_hash", sa.Text(), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scam_patterns")),
        sa.UniqueConstraint("slug", name=op.f("uq_scam_patterns_slug")),
    )
    op.create_index(
        "ix_scam_patterns_embedding_hnsw",
        "scam_patterns",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.create_table(
        "url_cache",
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "checked_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("url", name=op.f("pk_url_cache")),
    )
    op.create_table(
        "reports",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column("analysis_id", sa.UUID(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["analysis_id"],
            ["analyses.id"],
            name=op.f("fk_reports_analysis_id_analyses"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["entity_id"],
            ["reported_entities.id"],
            name=op.f("fk_reports_entity_id_reported_entities"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reports")),
    )
    op.create_index(op.f("ix_reports_analysis_id"), "reports", ["analysis_id"], unique=False)
    op.create_index(op.f("ix_reports_entity_id"), "reports", ["entity_id"], unique=False)
    # ### end Alembic commands ###

    # Supabase exposes the public schema via its REST API (anon/authenticated roles).
    # RLS with no policies blocks that API entirely; the backend connects as the table
    # owner, which bypasses RLS.
    for table in TABLES:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_reports_entity_id"), table_name="reports")
    op.drop_index(op.f("ix_reports_analysis_id"), table_name="reports")
    op.drop_table("reports")
    op.drop_table("url_cache")
    op.drop_index(
        "ix_scam_patterns_embedding_hnsw",
        table_name="scam_patterns",
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.drop_table("scam_patterns")
    op.drop_table("reported_entities")
    op.drop_index("ix_analyses_created_at", table_name="analyses")
    op.drop_table("analyses")
    # ### end Alembic commands ###
    # The vector extension is intentionally left installed; other objects may use it.
