"""scam pattern kind

Adds scam_patterns.kind: 'scam' for scam patterns, 'genuine' for legitimate messages that
are easily mistaken for scams (the pattern signal compares against both).

Revision ID: a16312ca1083
Revises: b269ef487104
Create Date: 2026-09-28 00:00:27.240455

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a16312ca1083"
down_revision: str | Sequence[str] | None = "b269ef487104"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "scam_patterns",
        sa.Column("kind", sa.Text(), server_default=sa.text("'scam'"), nullable=False),
    )
    # ### end Alembic commands ###
    op.create_check_constraint(
        op.f("ck_scam_patterns_kind"), "scam_patterns", "kind IN ('scam', 'genuine')"
    )


def downgrade() -> None:
    op.drop_constraint(op.f("ck_scam_patterns_kind"), "scam_patterns", type_="check")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("scam_patterns", "kind")
    # ### end Alembic commands ###
