"""analysis advice and language

Revision ID: b269ef487104
Revises: 37ae95149788
Create Date: 2026-09-27 18:45:55.927000

"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b269ef487104"
down_revision: str | Sequence[str] | None = "37ae95149788"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "analyses",
        sa.Column(
            "advice",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
    )
    op.add_column(
        "analyses",
        sa.Column(
            "similar_patterns",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
    )
    op.add_column("analyses", sa.Column("language_hint", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("analyses", "language_hint")
    op.drop_column("analyses", "similar_patterns")
    op.drop_column("analyses", "advice")
    # ### end Alembic commands ###
